### ISSUE TITLE
pip install pygame on anaconda mac error

### ISSUE THREAD

**Issue by kaotigger** [LanKuDot/MLGame#1]
If the anaconda python environment is python 3.5,   can not install pygame.
Solve: using python 3.6
I'm not sure whether using python 3.6 (the tutorial require python 3.5) will occur any unknown error ?

**Comment by LanKuDot** [comment]
Accroding to [the comment](https://github.com/pygame/pygame/issues/466#issuecomment-409616943) in the issue page of the pygame. The member said that there is no pygame build for python 3.5 on mac OS (only for 2.7, 3.6 and 3.7). 

In another comment said that pygame can be installed from the command line https://www.pygame.org/wiki/macintosh, but I don't know if it works.

**Comment by LanKuDot** [comment]
It's ok to use python 3.6+. The TA checked that the modules used in the class can be run on python 3.6+.
