### ISSUE TITLE
希望能增加指定執行哪個檔案的指令

### ISSUE THREAD

**Issue by nckuBluer** [LanKuDot/MLGame#2]
因為可能會有多個不同方法想測試，希望能在ml資料夾中放置不同檔名的py檔，並透過指令來指定要用哪個來執行，而不用每次有想測試時，還要將檔名改為ml_play.py

**Comment by LanKuDot** [comment]
了解。我建議一個方法讓你可以暫時解決這個問題。假設你有幾個不同的做法檔案: `ml_play_1.py`、`ml_play_2.py`，裏面都有執行的函式 `ml_loop()`。這樣在主檔案 `ml_play.py` 可以這樣寫：
```python
import arkanoid.ml.ml_play_1 as ml

def ml_loop():
    ml.ml_loop()
```
要換不同方法可以把 `arkanoid.ml.ml_play_1` 改成 `arkanoid.ml.ml_play_2`。注意這些檔案要在同一個資料夾中。

**Comment by nckuBluer** [comment]
收到~我會再試試，非常感謝您

Kun-Yi Li <notifications@github.com> 於 2019年3月31日 週日 下午11:40 寫道：

**Comment by LanKuDot** [comment]
Added at [Beta 2.2](https://github.com/LanKuDot/MLGame/releases/tag/beta2.2).
