### ISSUE TITLE
請教生成檔案資訊

### ISSUE THREAD

**Issue by nckuBluer** [LanKuDot/MLGame#3]
之前我執行完 python MLGame.py -f 24 arkanoid 3 -r  後會在MLGame_master的資料夾下看到game_inforxxxxx.pickle這個檔，為什麼我後來log file的時候就看不到了?是因為版本更新後就取消產生這個檔案嗎?還是因為有少打什麼指令呢?

另外我發現game_inforxxx.pickle裡plateform(第二個index)的資訊似乎跟在log資料夾下的pickle檔裡的plateform不太一樣(趨勢大致相同，但不完全符合)，請問是為什麼呢?

感謝您的回覆

**Comment by LanKuDot** [comment]
請問你用的程式碼是助教提供的嗎? 這個專案不會產生 `game_inforxxx.pickle` 這樣的檔案，只會生成 log 下面的 pickle 檔

**Comment by greatstudent** [comment]
同學你好
會產生game_inforxxx.pickle應該是你在ml_play.m裡有打了存檔的程式碼才會產生。
但那串是助教的示範程式，(應該是你在第一次寫rule時照打了助教的範例，才會每次遊戲都存gameinfor.pickle檔)。

gameinfor檔純粹是助教自己測試用的，第一堂課也有強調過那部分的程式你們不需要用。
所以請針對log資料夾裡的pickle檔去分析，分析方法都有公布於社團了。

**Comment by nckuBluer** [comment]
我剛剛回去檢查，的確是之前助教的範例code，之前沒有發現。很抱歉打擾助教了~

greatstudent <notifications@github.com> 於 2019年4月4日 週四 下午1:57寫道：
